ALTER TABLE giao_dich_xu
  MODIFY COLUMN loai_giao_dich ENUM(
    'THUONG_DANH_GIA', 'TICH_LUY_DON_HANG', 'HOAN_TAC_DANH_GIA',
    'THU_HOI_XU_HOAN_HANG', 'DIEU_CHINH_ADMIN', 'DIEM_DANH_HANG_NGAY'
  ) NOT NULL;
