ALTER TABLE don_hang
  ADD COLUMN xu_da_dung BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER tien_giam;

ALTER TABLE giao_dich_xu
  MODIFY COLUMN loai_giao_dich ENUM(
    'THUONG_DANH_GIA', 'TICH_LUY_DON_HANG', 'HOAN_TAC_DANH_GIA',
    'THU_HOI_XU_HOAN_HANG', 'DIEU_CHINH_ADMIN', 'DIEM_DANH_HANG_NGAY',
    'SU_DUNG_DON_HANG',
    'HOAN_XU_HUY_DON'
  ) NOT NULL;
